### ISSUE TITLE
Can someone add a title for this document?

### ISSUE THREAD

**Issue by praveenscience** [praveenscience/edusera-class-2-github-test#1]
This document `ReadMe.md` lacks a title. Can someone please add a suitable title for this document?

**Comment by Shivanshi-Sharma** [comment]
I want to do this.

**Comment by Nileshyadav735** [comment]
I Would Like to do it..

**Comment by praveenscience** [comment]
@Shivanshi-Sharma The issue is assigned to you, as you're the first person. Please start working on it.

**Comment by priyanshumishra87** [comment]
I also would like to do it

**Comment by sunkuraghu** [comment]
i also want to do it

**Comment by TheParthMaru** [comment]
Sir I would like to contribute

**Comment by praveenscience** [comment]
@Shivanshi-Sharma Since we are running out of time, we'll try to do the same with another person. 😊  You'll get another chance soon. 😊

**Comment by praveenscience** [comment]
@Nileshyadav735 Let's do it! 😊
